name: Upload Pre-trained Model to Hugging Face

on: 
  push:
    branches: 
      - main  

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Hugging Face Hub Library
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Log in to Hugging Face Hub
        run: |
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}  # Menggunakan token dari GitHub Secrets

      - name: Verify Login
        run: |
          huggingface-cli whoami  # Memverifikasi bahwa login berhasil

      - name: Upload Model to Hugging Face
        run: |
          huggingface-cli repo create trash --type model --organization InnovateXLab --private --yes

          python -m huggingface_hub.upload_file \
            --path_or_file notebooks/simpan_resnet_model.h5 \
            --repo_id InnovateXLab/trash \
            --repo_type model \
            --token ${{ secrets.HF_TOKEN }}