name: Deploy to Hugging Face

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Change to your Python version
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Login to Hugging Face Hub 
        uses: osbm/huggingface-login@v0.0.1
        with:
          username: ${{ secrets.HD_USERNAME }}
          key: ${{ secrets.HF_TOKEN }}  # Use `token` if `password` is not supported
          add_to_git_credentials: false

      - name: Check if logged in   
        run: huggingface-cli whoami

      - name: Push and Sync to Hugging Face Repo    
        uses: backendcloud/hugging-push@v0.2.3
        with:
          #huggingface_repo: 'kerjaaa/trashhh'  # Replace with the target repo ID
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: false  
          space_sdk: 'gradio'
