# GitHub Actions workflow file
name: Model Training and Evaluation

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Run Training
        run: python src/train_model.py  

      - name: Upload to Hugging Face
        if: ${{ success() }}  
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Pastikan untuk menyimpan token di Secrets GitHub dengan nama 'HF_TOKEN'
        run: |
          echo $HF_TOKEN | huggingface-cli login
          huggingface-cli repo create trash --type model --organization InnovateXLab --private
          huggingface-cli upload simpan_resnet_model.h5 --repo trash --path "/"
