# GitHub Actions workflow file
name: Model Training and Evaluation

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Run Training
        run: python src/train_model.py  

      - name: Upload to Hugging Face
        if: success()  
        run: |
          huggingface-cli login --token ${{ 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 }}
          huggingface-cli repo create your_model_name --type model --organization your_organization_name --private
          huggingface-cli upload simpan_resnet_model.h5 --repo your_model_name --path "/"
