name: Upload Pre-trained Model to Hugging Face

on: 
  push:
    branches: 
      - main  

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Hugging Face Hub Library
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Upload Model to Hugging Face
        run: |
          python -m huggingface_hub.upload_file \
            --path_or_file notebooks/simpan_resnet_model.h5 \
            --repo_id kerjaaa/trash \
            --repo_type model \
            --token ${{ secrets.HF_TOKEN }}  # Menggunakan token dari GitHub Secrets

name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: anee/huggingface-sync-action@v0.0.1
      with:
        github_repo_id: anekekarina99/aitask
        huggingface_repo_id: kerjaaa/trash
        repo_type: model
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN }}