name: Upload Pre-trained Model to Hugging Face

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches:
      - main  

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Hugging Face Hub Library
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub  # Install library untuk upload ke Hugging Face

      - name: Log in to Hugging Face Hub
        run: |
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Upload Model to Hugging Face
        run: |
          # Membuat repo model (dengan opsi `--yes` untuk skip prompt konfirmasi)
          huggingface-cli repo create trash --type model --organization InnovateXLab --private --yes

          # Menggunakan huggingface_hub untuk upload file .h5
          python -m huggingface_hub.upload_file \
            --path_or_file notebooks/simpan_resnet_model.h5 \  # Path file .h5
            --repo_id InnovateXLab/trash \  # Sesuaikan nama organisasi dan repo
            --repo_type model \
            --token ${{ secrets.HF_TOKEN }}